drop TABLE HorseTracking.dbo.TakePart
drop TABLE HorseTracking.dbo.Activity 
drop TABLE HorseTracking.dbo.Eat
drop TABLE HorseTracking.dbo.Shared 
drop TABLE HorseTracking.dbo.Visit 
drop TABLE HorseTracking.dbo.CustomNotification
drop TABLE HorseTracking.dbo.Horse 
drop TABLE HorseTracking.dbo.UserAcount
drop TABLE HorseTracking.dbo.Feeding 
drop TABLE HorseTracking.dbo.Doctor
drop TABLE HorseTracking.dbo.Forage
drop TABLE HorseTracking.dbo.Competition
drop TABLE HorseTracking.dbo.DoctorSpecialisation
drop TABLE HorseTracking.dbo.UnitOfMeasure
drop TABLE HorseTracking.dbo.Meal
drop TABLE HorseTracking.dbo.HorseGender
drop TABLE HorseTracking.dbo.HorseStatus
drop TABLE HorseTracking.dbo.NutritionPlan 
drop TABLE HorseTracking.dbo.PeopleDetails
drop TABLE HorseTracking.dbo.UserType