// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HorseTrackingDesktop.Models
{
    public partial class Activities
    {
        public int ActivityId { get; set; }
        public int UserId { get; set; }
        public int ActivityType { get; set; }
        public int? TrainerId { get; set; }
        public int HorseId { get; set; }
        public DateTime Date { get; set; }
        public string Description { get; set; }
        public int? Time { get; set; }
        public int Intensivity { get; set; }
        public int Satisfaction { get; set; }

        public virtual Horses Horse { get; set; }
        public virtual UserAcounts Trainer { get; set; }
        public virtual UserAcounts User { get; set; }
    }
}