// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HorseTrackingDesktop.Models
{
    public partial class Contests
    {
        public Contests()
        {
            Participations = new HashSet<Participations>();
        }

        public int ContestId { get; set; }
        public string Level { get; set; }
        public string Name { get; set; }
        public int CompetitionId { get; set; }

        public virtual Competitions Competition { get; set; }
        public virtual ICollection<Participations> Participations { get; set; }
    }
}