// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HorseTrackingDesktop.Models
{
    public partial class DoctorSpecialisation
    {
        public DoctorSpecialisation()
        {
            Doctor = new HashSet<Doctor>();
        }

        public int SpecialisationId { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Doctor> Doctor { get; set; }
    }
}