// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HorseTrackingDesktop.Models
{
    public partial class Eat
    {
        public int EatId { get; set; }
        public int NutritionPlanId { get; set; }
        public int HorseId { get; set; }

        public virtual Horse Horse { get; set; }
        public virtual NutritionPlan NutritionPlan { get; set; }
    }
}