// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HorseTrackingDesktop.Models
{
    public partial class Forages
    {
        public Forages()
        {
            Portions = new HashSet<Portions>();
        }

        public int ForageId { get; set; }
        public string Name { get; set; }
        public int UnitId { get; set; }
        public string Producent { get; set; }
        public double? Capacity { get; set; }

        public virtual UnitOfMeasures Unit { get; set; }
        public virtual ICollection<Portions> Portions { get; set; }
    }
}