// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HorseTrackingDesktop.Models
{
    public partial class Forage
    {
        public Forage()
        {
            Feeding = new HashSet<Feeding>();
        }

        public int ForageId { get; set; }
        public string Name { get; set; }
        public int UnitOfMeasure { get; set; }
        public string Producent { get; set; }
        public int? Capacity { get; set; }

        public virtual UnitOfMeasure UnitOfMeasureNavigation { get; set; }
        public virtual ICollection<Feeding> Feeding { get; set; }
    }
}