// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HorseTrackingDesktop.Models
{
    public partial class Horses
    {
        public Horses()
        {
            Activities = new HashSet<Activities>();
            Diets = new HashSet<Diets>();
            Notifications = new HashSet<Notifications>();
            Participations = new HashSet<Participations>();
            Shareds = new HashSet<Shareds>();
            Visits = new HashSet<Visits>();
        }

        public int HorseId { get; set; }
        public int GenderId { get; set; }
        public int UserId { get; set; }
        public int StatusId { get; set; }
        public string Name { get; set; }
        public string Mother { get; set; }
        public string Father { get; set; }
        public DateTime? Birthday { get; set; }
        public string Race { get; set; }
        public string Breeder { get; set; }
        public string Passport { get; set; }
        public string Photo { get; set; }

        public virtual HorseGenders Gender { get; set; }
        public virtual Status Status { get; set; }
        public virtual UserAcounts User { get; set; }
        public virtual ICollection<Activities> Activities { get; set; }
        public virtual ICollection<Diets> Diets { get; set; }
        public virtual ICollection<Notifications> Notifications { get; set; }
        public virtual ICollection<Participations> Participations { get; set; }
        public virtual ICollection<Shareds> Shareds { get; set; }
        public virtual ICollection<Visits> Visits { get; set; }
    }
}