// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HorseTrackingDesktop.Models
{
    public partial class HorseGenders
    {
        public HorseGenders()
        {
            Horses = new HashSet<Horses>();
        }

        public int GenderId { get; set; }
        public string Gender { get; set; }

        public virtual ICollection<Horses> Horses { get; set; }
    }
}