// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HorseTrackingDesktop.Models
{
    public partial class MealNames
    {
        public MealNames()
        {
            Meals = new HashSet<Meals>();
        }

        public int MealNameId { get; set; }
        public string MealName { get; set; }

        public virtual ICollection<Meals> Meals { get; set; }
    }
}