// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HorseTrackingDesktop.Models
{
    public partial class Meals
    {
        public Meals()
        {
            Portions = new HashSet<Portions>();
        }

        public int MealId { get; set; }
        public string Hour { get; set; }
        public int MealNameId { get; set; }
        public int NutritionPlanId { get; set; }

        public virtual MealNames MealName { get; set; }
        public virtual NutritionPlans NutritionPlan { get; set; }
        public virtual ICollection<Portions> Portions { get; set; }
    }
}