// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HorseTrackingDesktop.Models
{
    public partial class Notifications
    {
        public int NotificationId { get; set; }
        public int UserId { get; set; }
        public int? HorseId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public DateTime SendDate { get; set; }
        public DateTime CreatedDate { get; set; }
        public bool TurnOn { get; set; }

        public virtual Horses Horse { get; set; }
        public virtual UserAcounts User { get; set; }
    }
}