// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HorseTrackingDesktop.Models
{
    public partial class NutritionPlan
    {
        public NutritionPlan()
        {
            Eat = new HashSet<Eat>();
            Feeding = new HashSet<Feeding>();
        }

        public int NutritionPlanId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int Icon { get; set; }

        public virtual ICollection<Eat> Eat { get; set; }
        public virtual ICollection<Feeding> Feeding { get; set; }
    }
}