// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HorseTrackingDesktop.Models
{
    public partial class Participations
    {
        public int ParticipationId { get; set; }
        public int HorseId { get; set; }
        public int ContestId { get; set; }
        public string Result { get; set; }
        public int? Place { get; set; }

        public virtual Contests Contest { get; set; }
        public virtual Horses Horse { get; set; }
    }
}