// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HorseTrackingDesktop.Models
{
    public partial class PeopleDetails
    {
        public PeopleDetails()
        {
            Professionals = new HashSet<Professionals>();
            UserAcounts = new HashSet<UserAcounts>();
        }

        public int DetailId { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public string Number { get; set; }
        public string PostalCode { get; set; }

        public virtual ICollection<Professionals> Professionals { get; set; }
        public virtual ICollection<UserAcounts> UserAcounts { get; set; }
    }
}