// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HorseTrackingDesktop.Models
{
    public partial class PeopleDetails
    {
        public PeopleDetails()
        {
            Doctor = new HashSet<Doctor>();
            UserAcount = new HashSet<UserAcount>();
        }

        public int DetailsId { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public string Number { get; set; }

        public virtual ICollection<Doctor> Doctor { get; set; }
        public virtual ICollection<UserAcount> UserAcount { get; set; }
    }
}