// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HorseTrackingDesktop.Models
{
    public partial class Professionals
    {
        public Professionals()
        {
            Visits = new HashSet<Visits>();
        }

        public int ProfessionalId { get; set; }
        public string Degree { get; set; }
        public int SpecialisationId { get; set; }
        public int DetailId { get; set; }

        public virtual PeopleDetails Detail { get; set; }
        public virtual Specialisations Specialisation { get; set; }
        public virtual ICollection<Visits> Visits { get; set; }
    }
}