// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HorseTrackingDesktop.Models
{
    public partial class Shared
    {
        public int SharedId { get; set; }
        public int HorseId { get; set; }
        public int UserShareId { get; set; }
        public int UserScanId { get; set; }
        public DateTime EndDate { get; set; }
        public DateTime StartDate { get; set; }
        public string Code { get; set; }

        public virtual Horse Horse { get; set; }
        public virtual UserAcount UserScan { get; set; }
        public virtual UserAcount UserShare { get; set; }
    }
}