// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HorseTrackingDesktop.Models
{
    public partial class TakePart
    {
        public int TakePartId { get; set; }
        public int HorseId { get; set; }
        public int CompetitionId { get; set; }
        public string Level { get; set; }
        public string Result { get; set; }
        public int? Place { get; set; }

        public virtual Competition Competition { get; set; }
        public virtual Horse Horse { get; set; }
    }
}