// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HorseTrackingDesktop.Models
{
    public partial class UnitOfMeasures
    {
        public UnitOfMeasures()
        {
            Forages = new HashSet<Forages>();
            Portions = new HashSet<Portions>();
        }

        public int UnitId { get; set; }
        public string UnitName { get; set; }

        public virtual ICollection<Forages> Forages { get; set; }
        public virtual ICollection<Portions> Portions { get; set; }
    }
}