// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HorseTrackingDesktop.Models
{
    public partial class UserType
    {
        public UserType()
        {
            UserAcount = new HashSet<UserAcount>();
        }

        public int TypeId { get; set; }
        public string TypeName { get; set; }

        public virtual ICollection<UserAcount> UserAcount { get; set; }
    }
}