// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HorseTrackingDesktop.Models
{
    public partial class UserAcount
    {
        public UserAcount()
        {
            ActivityTrainer = new HashSet<Activity>();
            ActivityUser = new HashSet<Activity>();
            CustomNotification = new HashSet<CustomNotification>();
            Horse = new HashSet<Horse>();
            SharedUserScan = new HashSet<Shared>();
            SharedUserShare = new HashSet<Shared>();
        }

        public int UserId { get; set; }
        public int UserTypeId { get; set; }
        public int DetailsId { get; set; }
        public string AcountLogin { get; set; }
        public string Hash { get; set; }
        public string Salt { get; set; }
        public DateTime? CreatedDate { get; set; }

        public virtual PeopleDetails Details { get; set; }
        public virtual UserType UserType { get; set; }
        public virtual ICollection<Activity> ActivityTrainer { get; set; }
        public virtual ICollection<Activity> ActivityUser { get; set; }
        public virtual ICollection<CustomNotification> CustomNotification { get; set; }
        public virtual ICollection<Horse> Horse { get; set; }
        public virtual ICollection<Shared> SharedUserScan { get; set; }
        public virtual ICollection<Shared> SharedUserShare { get; set; }

        public static UserAcount CurrentUser { get; set; }= new UserAcount();
    }
}