// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HorseTrackingDesktop.Models
{
    public partial class UserTypes
    {
        public UserTypes()
        {
            UserAcounts = new HashSet<UserAcounts>();
        }

        public int TypeId { get; set; }
        public string TypeName { get; set; }

        public virtual ICollection<UserAcounts> UserAcounts { get; set; }
    }
}