// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HorseTrackingDesktop.Models
{
    public partial class Visits
    {
        public int VisitId { get; set; }
        public int ProfessionalId { get; set; }
        public int HorseId { get; set; }
        public DateTime VisitDate { get; set; }
        public string Summary { get; set; }
        public string Image { get; set; }
        public double? Cost { get; set; }

        public virtual Horses Horse { get; set; }
        public virtual Professionals Professional { get; set; }
    }
}