// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HorseTrackingDesktop.Models
{
    public partial class Visit
    {
        public int CareId { get; set; }
        public int DoctorId { get; set; }
        public int HorseId { get; set; }
        public DateTime VisitDate { get; set; }
        public string Summary { get; set; }
        public string ArtefactImage { get; set; }
        public double? Cost { get; set; }

        public virtual Doctor Doctor { get; set; }
        public virtual Horse Horse { get; set; }
    }
}