INSERT INTO HorseTracking.dbo.UserTypes (typeName)
VALUES ('admin')
INSERT INTO HorseTracking.dbo.UserTypes (typeName)
VALUES ('appOwner')
INSERT INTO HorseTracking.dbo.UserTypes (typeName)
VALUES ('horseOwner')
INSERT INTO HorseTracking.dbo.UserTypes (typeName)
VALUES ('trainer')

INSERT INTO HorseTracking.dbo.Status (name)
VALUES ('active')
INSERT INTO HorseTracking.dbo.Status (name)
VALUES ('inactive')
INSERT INTO HorseTracking.dbo.Status (name)
VALUES ('sent')
INSERT INTO HorseTracking.dbo.Status (name)
VALUES ('shared')

INSERT INTO HorseTracking.dbo.HorseGenders (gender)
VALUES ('klacz')
INSERT INTO HorseTracking.dbo.HorseGenders (gender)
VALUES ('ogier')
INSERT INTO HorseTracking.dbo.HorseGenders (gender)
VALUES ('wa³ach')

INSERT INTO HorseTracking.dbo.UnitOfMeasures(unitName)
VALUES('kilogram')
INSERT INTO HorseTracking.dbo.UnitOfMeasures(unitName)
VALUES('dekagram')
INSERT INTO HorseTracking.dbo.UnitOfMeasures(unitName)
VALUES('gram')
INSERT INTO HorseTracking.dbo.UnitOfMeasures(unitName)
VALUES('liter')
INSERT INTO HorseTracking.dbo.UnitOfMeasures(unitName)
VALUES('mililiter')
INSERT INTO HorseTracking.dbo.UnitOfMeasures(unitName)
VALUES('bala')
INSERT INTO HorseTracking.dbo.UnitOfMeasures(unitName)
VALUES('sztuka')
INSERT INTO HorseTracking.dbo.UnitOfMeasures(unitName)
VALUES('miarka')